const TAROT_CARDS = [
  // Major Arcana (22)
  { id:0,  name:'바보',           nameEn:'The Fool',          arcana:'major', upright:'새로운 시작, 순수함, 자발성, 모험', reversed:'무모함, 위험, 어리석음' },
  { id:1,  name:'마법사',         nameEn:'The Magician',      arcana:'major', upright:'의지력, 기술, 집중, 실현', reversed:'조작, 재능 낭비, 사기' },
  { id:2,  name:'여교황',         nameEn:'High Priestess',    arcana:'major', upright:'직관, 신성한 지혜, 내면의 목소리', reversed:'비밀, 억압된 직관, 혼란' },
  { id:3,  name:'여황제',         nameEn:'The Empress',       arcana:'major', upright:'풍요, 창조, 모성, 자연', reversed:'창의성 저하, 과잉의존, 불임' },
  { id:4,  name:'황제',           nameEn:'The Emperor',       arcana:'major', upright:'권위, 구조, 안정, 리더십', reversed:'지배욕, 경직성, 무능한 통제' },
  { id:5,  name:'교황',           nameEn:'The Hierophant',    arcana:'major', upright:'전통, 제도, 영적 안내, 가르침', reversed:'반항, 변화, 기존 틀 거부' },
  { id:6,  name:'연인',           nameEn:'The Lovers',        arcana:'major', upright:'사랑, 조화, 관계, 선택', reversed:'부조화, 이별, 갈등, 나쁜 선택' },
  { id:7,  name:'전차',           nameEn:'The Chariot',       arcana:'major', upright:'승리, 의지, 통제, 자기주도', reversed:'공격성, 결핍된 방향성, 패배' },
  { id:8,  name:'힘',             nameEn:'Strength',          arcana:'major', upright:'용기, 내면의 힘, 인내, 자제력', reversed:'자기의심, 나약함, 통제 상실' },
  { id:9,  name:'은둔자',         nameEn:'The Hermit',        arcana:'major', upright:'내면 탐구, 고독, 안내, 성찰', reversed:'고립, 외로움, 미성숙, 거부' },
  { id:10, name:'운명의 수레바퀴', nameEn:'Wheel of Fortune', arcana:'major', upright:'운, 변화, 순환, 전환점', reversed:'불운, 저항, 나쁜 타이밍' },
  { id:11, name:'정의',           nameEn:'Justice',           arcana:'major', upright:'공정성, 진실, 균형, 원인과 결과', reversed:'불공정, 불균형, 편견' },
  { id:12, name:'매달린 남자',     nameEn:'The Hanged Man',   arcana:'major', upright:'일시정지, 희생, 새로운 관점', reversed:'지연, 저항, 무의미한 희생' },
  { id:13, name:'죽음',           nameEn:'Death',             arcana:'major', upright:'끝과 새 시작, 변화, 전환', reversed:'변화 저항, 정체, 집착' },
  { id:14, name:'절제',           nameEn:'Temperance',        arcana:'major', upright:'균형, 인내, 목적, 조화', reversed:'불균형, 과잉, 자기치유 필요' },
  { id:15, name:'악마',           nameEn:'The Devil',         arcana:'major', upright:'집착, 속박, 물질주의, 중독', reversed:'해방, 자유, 집착 극복' },
  { id:16, name:'탑',             nameEn:'The Tower',         arcana:'major', upright:'갑작스러운 변화, 혼돈, 각성', reversed:'변화 회피, 점진적 붕괴' },
  { id:17, name:'별',             nameEn:'The Star',          arcana:'major', upright:'희망, 영감, 평온, 재생', reversed:'절망, 믿음 상실, 낙담' },
  { id:18, name:'달',             nameEn:'The Moon',          arcana:'major', upright:'환상, 두려움, 무의식, 혼란', reversed:'혼란 해소, 진실 드러남' },
  { id:19, name:'태양',           nameEn:'The Sun',           arcana:'major', upright:'성공, 기쁨, 활력, 낙관', reversed:'일시적 우울, 과잉낙관' },
  { id:20, name:'심판',           nameEn:'Judgement',         arcana:'major', upright:'반성, 각성, 새 출발, 용서', reversed:'자기비판, 과거 집착' },
  { id:21, name:'세계',           nameEn:'The World',         arcana:'major', upright:'완성, 성취, 통합, 여행', reversed:'미완성, 지연, 완성 추구' },

  // Wands (14)
  { id:22, name:'완드 에이스',   nameEn:'Ace of Wands',      arcana:'wands', upright:'창의성, 새 벤처, 열정, 성장', reversed:'지연, 에너지 부족, 막힌 창의성' },
  { id:23, name:'완드 2',        nameEn:'Two of Wands',      arcana:'wands', upright:'계획, 미래 비전, 진보', reversed:'두려움, 우유부단, 계획 실패' },
  { id:24, name:'완드 3',        nameEn:'Three of Wands',    arcana:'wands', upright:'확장, 원대한 계획, 협업', reversed:'장애물, 지연, 단기적 사고' },
  { id:25, name:'완드 4',        nameEn:'Four of Wands',     arcana:'wands', upright:'축하, 조화, 귀향, 성취', reversed:'내적 갈등, 불안정, 부족한 지원' },
  { id:26, name:'완드 5',        nameEn:'Five of Wands',     arcana:'wands', upright:'경쟁, 갈등, 긴장감', reversed:'내적 갈등, 회피, 타협' },
  { id:27, name:'완드 6',        nameEn:'Six of Wands',      arcana:'wands', upright:'승리, 성공, 공적 인정', reversed:'자존심 타격, 실패, 불신' },
  { id:28, name:'완드 7',        nameEn:'Seven of Wands',    arcana:'wands', upright:'방어, 도전에 맞서기, 인내', reversed:'지침, 포기, 방어과잉' },
  { id:29, name:'완드 8',        nameEn:'Eight of Wands',    arcana:'wands', upright:'빠른 행동, 변화, 뉴스', reversed:'지연, 좌절, 내부 저항' },
  { id:30, name:'완드 9',        nameEn:'Nine of Wands',     arcana:'wands', upright:'회복력, 인내, 테스트', reversed:'방어적, 지침, 편집증' },
  { id:31, name:'완드 10',       nameEn:'Ten of Wands',      arcana:'wands', upright:'과중한 짐, 책임, 고생', reversed:'짐 내려놓기, 위임, 번아웃' },
  { id:32, name:'완드 시종',     nameEn:'Page of Wands',     arcana:'wands', upright:'탐험, 흥분, 자유분방', reversed:'새로운 생각 결여, 조급함' },
  { id:33, name:'완드 기사',     nameEn:'Knight of Wands',   arcana:'wands', upright:'에너지, 열정, 충동성, 모험', reversed:'충동적, 분노, 무모함' },
  { id:34, name:'완드 여왕',     nameEn:'Queen of Wands',    arcana:'wands', upright:'자신감, 독립성, 사회성', reversed:'질투, 불안감, 내성적' },
  { id:35, name:'완드 왕',       nameEn:'King of Wands',     arcana:'wands', upright:'비전, 기업가 정신, 명예', reversed:'충동적, 독단적, 성급함' },

  // Cups (14)
  { id:36, name:'컵 에이스',     nameEn:'Ace of Cups',       arcana:'cups', upright:'새로운 감정, 직관, 친밀감', reversed:'감정 저지, 내면 공허' },
  { id:37, name:'컵 2',          nameEn:'Two of Cups',        arcana:'cups', upright:'통합, 파트너십, 공통점', reversed:'자기사랑 결여, 파트너십 해체' },
  { id:38, name:'컵 3',          nameEn:'Three of Cups',      arcana:'cups', upright:'축하, 우정, 협업', reversed:'독립, 외로움, 과음' },
  { id:39, name:'컵 4',          nameEn:'Four of Cups',       arcana:'cups', upright:'명상, 무기력, 재평가', reversed:'새 기회 수용, 각성' },
  { id:40, name:'컵 5',          nameEn:'Five of Cups',       arcana:'cups', upright:'슬픔, 상실, 후회, 비탄', reversed:'수용, 앞으로 나아감, 용서' },
  { id:41, name:'컵 6',          nameEn:'Six of Cups',        arcana:'cups', upright:'향수, 어린 시절, 순수함', reversed:'과거 집착, 미성숙' },
  { id:42, name:'컵 7',          nameEn:'Seven of Cups',      arcana:'cups', upright:'환상, 선택, 소원 성취', reversed:'정렬, 개인적 가치, 선택 능력' },
  { id:43, name:'컵 8',          nameEn:'Eight of Cups',      arcana:'cups', upright:'떠나기, 희망 포기, 탈출', reversed:'두려움, 동기 부여, 돌아옴' },
  { id:44, name:'컵 9',          nameEn:'Nine of Cups',       arcana:'cups', upright:'만족, 물질적 행복, 소원 성취', reversed:'물질주의, 욕구불만, 탐욕' },
  { id:45, name:'컵 10',         nameEn:'Ten of Cups',        arcana:'cups', upright:'신성한 사랑, 행복, 조화', reversed:'행복 추구, 붕괴된 가치관' },
  { id:46, name:'컵 시종',       nameEn:'Page of Cups',       arcana:'cups', upright:'창의적 기회, 직관, 호기심', reversed:'감정적 미성숙, 꾀병' },
  { id:47, name:'컵 기사',       nameEn:'Knight of Cups',     arcana:'cups', upright:'창의성, 로맨스, 매력', reversed:'불순한 동기, 신뢰불가' },
  { id:48, name:'컵 여왕',       nameEn:'Queen of Cups',      arcana:'cups', upright:'공감, 돌봄, 정서적 안정', reversed:'내면 감정 무시, 불안정' },
  { id:49, name:'컵 왕',         nameEn:'King of Cups',       arcana:'cups', upright:'감정 균형, 온화함, 외교', reversed:'감정 조종, 억압' },

  // Swords (14)
  { id:50, name:'소드 에이스',   nameEn:'Ace of Swords',     arcana:'swords', upright:'돌파구, 명확성, 진실', reversed:'혼란, 잔인함, 부정직' },
  { id:51, name:'소드 2',        nameEn:'Two of Swords',     arcana:'swords', upright:'어려운 선택, 교착상태, 회피', reversed:'혼란, 정보 과부하, 갈등' },
  { id:52, name:'소드 3',        nameEn:'Three of Swords',   arcana:'swords', upright:'심장의 고통, 슬픔, 비탄', reversed:'긍정적 사고, 낙관주의, 용서' },
  { id:53, name:'소드 4',        nameEn:'Four of Swords',    arcana:'swords', upright:'휴식, 재활, 명상', reversed:'재개, 불안, 성급함' },
  { id:54, name:'소드 5',        nameEn:'Five of Swords',    arcana:'swords', upright:'갈등, 불일치, 패배', reversed:'화해, 평화, 과거를 떠나보냄' },
  { id:55, name:'소드 6',        nameEn:'Six of Swords',     arcana:'swords', upright:'전환, 변화, 여정', reversed:'저항, 떠나지 못함' },
  { id:56, name:'소드 7',        nameEn:'Seven of Swords',   arcana:'swords', upright:'배신, 기만, 전략', reversed:'양심의 가책, 고백' },
  { id:57, name:'소드 8',        nameEn:'Eight of Swords',   arcana:'swords', upright:'속박, 제한, 피해의식', reversed:'자유, 해방, 자아 수용' },
  { id:58, name:'소드 9',        nameEn:'Nine of Swords',    arcana:'swords', upright:'불안, 두려움, 공포', reversed:'내면의 요란함, 비밀' },
  { id:59, name:'소드 10',       nameEn:'Ten of Swords',     arcana:'swords', upright:'고통스러운 결말, 깊은 상처', reversed:'회복, 재기, 두려움 극복' },
  { id:60, name:'소드 시종',     nameEn:'Page of Swords',    arcana:'swords', upright:'새 아이디어, 호기심, 경계', reversed:'조작, 루머, 배신' },
  { id:61, name:'소드 기사',     nameEn:'Knight of Swords',  arcana:'swords', upright:'야망, 행동, 추진력', reversed:'무모함, 성급함, 무례함' },
  { id:62, name:'소드 여왕',     nameEn:'Queen of Swords',   arcana:'swords', upright:'복잡성, 독립성, 명석함', reversed:'냉혹함, 잔인함, 쓴맛' },
  { id:63, name:'소드 왕',       nameEn:'King of Swords',    arcana:'swords', upright:'지적 능력, 권위, 진실', reversed:'조용한 힘, 조종, 폭군' },

  // Pentacles (14)
  { id:64, name:'펜타클 에이스', nameEn:'Ace of Pentacles',  arcana:'pentacles', upright:'기회, 번영, 새로운 시작', reversed:'기회 상실, 재물 결핍' },
  { id:65, name:'펜타클 2',      nameEn:'Two of Pentacles',  arcana:'pentacles', upright:'균형, 멀티태스킹, 적응', reversed:'불균형, 과부하, 무계획' },
  { id:66, name:'펜타클 3',      nameEn:'Three of Pentacles',arcana:'pentacles', upright:'팀워크, 계획, 역량', reversed:'혼자 일함, 불화, 불일치' },
  { id:67, name:'펜타클 4',      nameEn:'Four of Pentacles', arcana:'pentacles', upright:'보안, 저축, 안정', reversed:'탐욕, 물질주의, 자기 보호' },
  { id:68, name:'펜타클 5',      nameEn:'Five of Pentacles', arcana:'pentacles', upright:'재정적 손실, 가난, 고립', reversed:'회복, 영적 성장' },
  { id:69, name:'펜타클 6',      nameEn:'Six of Pentacles',  arcana:'pentacles', upright:'관대함, 나눔, 번영', reversed:'빚, 탐욕, 이기심' },
  { id:70, name:'펜타클 7',      nameEn:'Seven of Pentacles',arcana:'pentacles', upright:'평가, 끈기, 투자', reversed:'성급함, 아무런 결과 없음' },
  { id:71, name:'펜타클 8',      nameEn:'Eight of Pentacles',arcana:'pentacles', upright:'근면, 기술 개발, 장인정신', reversed:'완벽주의, 동기 부족' },
  { id:72, name:'펜타클 9',      nameEn:'Nine of Pentacles', arcana:'pentacles', upright:'번영, 사치, 자기충족', reversed:'재정적 의존, 자기가치 과신' },
  { id:73, name:'펜타클 10',     nameEn:'Ten of Pentacles',  arcana:'pentacles', upright:'부, 안정, 가족, 유산', reversed:'가족 갈등, 재정 실패' },
  { id:74, name:'펜타클 시종',   nameEn:'Page of Pentacles', arcana:'pentacles', upright:'학습 의욕, 새 기회, 출발', reversed:'결핍, 비현실적 목표' },
  { id:75, name:'펜타클 기사',   nameEn:'Knight of Pentacles',arcana:'pentacles',upright:'효율성, 근면, 책임감', reversed:'지루함, 완고함, 게으름' },
  { id:76, name:'펜타클 여왕',   nameEn:'Queen of Pentacles',arcana:'pentacles', upright:'풍요, 실용성, 양육', reversed:'자기중심성, 질투, 물질주의' },
  { id:77, name:'펜타클 왕',     nameEn:'King of Pentacles', arcana:'pentacles', upright:'부, 사업, 리더십, 보안', reversed:'완고함, 물질주의, 실패' }
];

// Spread positions by product type
const SPREAD_POSITIONS = {
  daily:         ['오늘의 메시지'],
  three:         ['과거', '현재', '미래'],
  yearly:        ['상반기', '하반기', '전반적 흐름'],
  comprehensive: ['연애/감정', '직업/목표', '재물/금전', '건강/에너지', '종합 조언'],
  celtic:        ['현재 상황', '도전/장애물', '잠재의식', '과거', '가능한 미래', '단기 미래', '나의 태도', '외부 영향', '희망/두려움', '최종 결과'],
  saju:          ['본질적 에너지', '현재 운세', '사주 보완', '관계의 흐름', '재물의 흐름', '건강/활력', '올해 방향', '내년 준비', '장기 비전', '핵심 조언']
};
